security:
  enable_authenticator_manager: true

    # ...
  encoders:
    # this internal class is used by Symfony to represent in-memory users
    Symfony\Component\Security\Core\User\User: 'auto'

  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    users_asd:
      id: App\Provider\UserProvider
#      memory:
#        users:
#          admin: {password: '1$FZajsD657mk05y0/7lUEvw$6vzoiw1xx9Puh90XFPrcvt/QaCnl5WiP38l0ftlWtRw', roles: ['ROLE_USER', 'ROLE_ADMIN']}
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      logout: ~
      provider: users_asd
      guard:
        authenticators:
          - App\Authenticator\JWTAuthenticator
