<?php


namespace App\Controller;


use App\Facade\JWT;
use Symfony\Component\HttpFoundation\JsonResponse;

class AbstractController extends \Symfony\Bundle\FrameworkBundle\Controller\AbstractController
{
    protected function json($data, int $status = 200, array $headers = [], array $context = []): JsonResponse
    {
        $data["meta"] = [
            "jwt_token" => JWT::encode(null),
            "loggedIn" => true
        ];
        return parent::json($data, $status, $headers, $context); // TODO: Change the autogenerated stub
    }
}